const GeneralInfo = () => {
  return (
    <><span
      className="w-full">TESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTESTTEST</span></>
  );
};

export default GeneralInfo;